### PR TITLE
Fixing Issue https://github.com/TeamMentor/TM_4_0_Design/issues/330

### PR DESCRIPTION
**Pull request by michaelhidalgo**
Fixing Issue https://github.com/TeamMentor/TM_4_0_Design/issues/330

### CODE REVIEW

**Comment by DinisCruz** [comment]
Hi @michaelhidalgo can you add tests that confirm the fix?

**Comment by michaelhidalgo** [comment]
yap, they are part of the QA project that I'll push.



2015-01-31 3:15 GMT-06:00 Dinis Cruz <notifications@github.com>:

> Hi @michaelhidalgo <https://github.com/michaelhidalgo> can you add tests
> that confirm the fix?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/TeamMentor/TM_4_0_Design/pull/358#issuecomment-72310619>
> .
>



-- 
Michael Hidalgo
http://michaelhidalgocr.blogspot.com

*The future has many names: For the weak, it means the unattainable. For
the fearful, it means the unknown. For the courageous, it means
opportunity. (1802-1885) French Poet, Dramatist, Writer*

**Comment by DinisCruz** [comment]
since this is a change on how the page is rendered (on the TM Design side), can you also add some tests to the TM_Design project (using supertest).

You can also use cheerio to access the 'html input element attribute' values programatically

See this test for an example of the type of test that I'm thinking of: https://github.com/TeamMentor/TM_4_0_Design/blob/master/node/tests/controllers/Library-Controller.test.coffee#L170-L181

**Comment by michaelhidalgo** [comment]
Really cool. Sure I'm going to play with it :)

2015-01-31 8:11 GMT-06:00 Dinis Cruz <notifications@github.com>:

> since this is a change on how the page is rendered (on the TM Design
> side), can you also add some tests to the TM_Design project (using
> supertest).
>
> You can also use cheerio to access the 'html input element attribute'
> values programatically
>
> See this test for an example of the type of test that I'm thinking of:
> https://github.com/TeamMentor/TM_4_0_Design/blob/master/node/tests/controllers/Library-Controller.test.coffee#L170-L181
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/TeamMentor/TM_4_0_Design/pull/358#issuecomment-72319176>
> .
>



-- 
Michael Hidalgo
http://michaelhidalgocr.blogspot.com

*The future has many names: For the weak, it means the unattainable. For
the fearful, it means the unknown. For the courageous, it means
opportunity. (1802-1885) French Poet, Dramatist, Writer*

**Comment by michaelhidalgo** [comment]
@DinisCruz can you please take a look at this test and let me know if it makes sense?
https://github.com/michaelhidalgo/TM_4_0_Design/blob/Dev/node/tests/controllers/Login-Controller.test.coffee#L185

This test uses the res.render, so not HTML will be rendered. I'm able to get the view model and verify that those values are persisted and sent to the UI.

**Comment by DinisCruz** [comment]
Looks great, merging

**Pull request merged**
