### PR TITLE
Issue 551 tm not available

### PR DESCRIPTION
**Pull request by michaelhidalgo**
Fixing issue https://github.com/TeamMentor/TM_4_0_Design/issues/551

### CODE REVIEW

**Comment by DinisCruz** [comment]
oops, this was done to master, @michaelhidalgo can you resubmit to dev (i'm going to reset master to the previous commit)

**Comment by DinisCruz** [comment]
@michaelhidalgo I've reset master to the previous commit (which was https://github.com/TeamMentor/TM_4_0_Design/commit/4077eefbbfaad478ff3a2f2d8c6914156dc7745e )

**Comment by michaelhidalgo** [comment]
thanks @DinisCruz , sorry for sending it to the wrong place :)

**Comment by DinisCruz** [comment]
no probs, it happens :)

**Pull request merged**
