### PR TITLE
Issue 208 add security headers

### PR DESCRIPTION
**Pull request by tekgirl77**

### CODE REVIEW

**Comment by tekgirl77** [comment]
https://mathiasbynens.be/notes/csp-reports

**Comment by DinisCruz** [comment]
@tekgirl77 when you have a nice link like https://mathiasbynens.be/notes/csp-reports make sure you add it to the actually issue (something even on the main body of the issue): https://github.com/TeamMentor/TM_4_0_Design/issues/208

That makes it easy to find in the future

**Comment by tekgirl77** [comment]
Okay  :)


Salle Ingle
Support & Implementation Specialist, eLearning
[image: https://www.securityinnovation.com/_img/art/logo.png]

**Comment by DinisCruz** [comment]
@tekgirl77 this is pointing to the **master** branch. You need to submit the PR to the **Issue_208_Security_Headers** branch

**Comment by tekgirl77** [comment]
oh sorry... okay, let me take a look at it...


Salle Ingle
Support & Implementation Specialist, eLearning
[image: https://www.securityinnovation.com/_img/art/logo.png]

**Comment by DinisCruz** [comment]
You also need to sync your code with the latest **dev** branch, since you are a bit behind

image

**Comment by tekgirl77** [comment]
ok... I've been syncing it w/ master... let me look at that too...


Salle Ingle
Support & Implementation Specialist, eLearning
[image: https://www.securityinnovation.com/_img/art/logo.png]

**Pull request closed without merging**
